### ISSUE TITLE
Sidney Lau Romanization

### ISSUE THREAD

**Issue by LawranceFung** [jyutnet/cantonese-books-data#10]
For those who prefer Sidney Lau romanization or like it as a supplement because of its finer-grain annotation of tones, are there any plans to support Sidney Lau Romanization in the jyut.net dictionary webapp?

**Comment by jyutnet** [comment]
Hi,

The website did support different romanization schemes, but the feature was removed in 2018 because of the added complexity in maintenance. And there is no plan to reintroduce this feature. Sorry about that.

**Comment by LawranceFung** [comment]
Is there a good source of data that's been digitized, distinguishing the high level from the high falling tone?  I'm not a big fan of Sidney Lau otherwise.

**Comment by jyutnet** [comment]
I don't think so. I remember two sources that I processed do mention the so-called "super high flat tone":

1. In 黃錫凌's 粵音韻彙, there are six entries that are annotated with "超平調". You can search for the asterisk (*) character under the 超平調標記 column in the data file to find them.

2. In 馮田獵's 粵語同音字典 (1996 edition), there are Seven entries are marked with "超高平", all of which are Cantonese colloquial characters. By the way, one entry is marked with "變高上".

But according to Wong, 超平調 is a even higher 高平調 (55) (P.72), i.e. the tone level is about 66. Wong doesn't differentiate between 高平 (55) and 高降 (53). In fact, he treats them as free variants (P.69). No explanation about 超高平 is given in Fung's book, but I bet it's the same as Wong's 超平調. I haven't read Sidney Lau's book, but from his website the "high flat" and "high falling" are the 高平 and 高降 tones respectively.

**Comment by LawranceFung** [comment]
Ok, thanks, the only I've been able to find on the 高降 tone is from Yale and Sidney Lau, which are rarely digitized.
