### ISSUE TITLE
英華分韻撮要 Character typo of Page 101 to 200

### ISSUE THREAD

**Issue by HayaoAkiyama** [jyutnet/cantonese-books-data#12]
Page119 "髻" shall be "䯻"

Page122 "械" was printed as "𢬿"

Page128 "巹" was printed as "𢀿"

Page142 "寇" shall be "宼"

Page142 "蔻" shall be "𦶲"

Page149 "屺" was printed as "𡵆"

Page149 "杞" was printed as "𣏌"

Page156 "汧" was printed as "汧"

Page156 "豜" was printed as "豣"

Page183 "舉" was printed as "𦦙"

Page193 "営" shall be "𬋩(⿳爫冖㠯)" (u2c2e9)

**Comment by jyutnet** [comment]
Thanks again!

> Page156 "汧" was printed as "汧"

My copy shows the reverse ("汧" printed as "汧"), and the data file reflects this. So I suppose no change is needed?
