### ISSUE TITLE
1856_英華分韻撮要 Pronunciation typo

### ISSUE THREAD

**Issue by HayaoAkiyama** [jyutnet/cantonese-books-data#18]
Page 5 , 遏 , at --> át
Page 179 , 孤 , ku --> kú
Page 179 , 沽 , ku --> kú
Page 179 , 酤 , ku --> kú
Page 179 , 姑 , ku --> kú
Page 179 , 蛄 , ku --> kú
Page 179 , 鴣 , ku --> kú
Page 179 , 辜 , ku --> kú
Page 179 , 觚 , ku --> kú
Page 179 , 柧 , ku --> kú
Page 179 , 罛 , ku --> kú
Page 179 , 罟 , ku --> kú
Page 180 , 菇,菰 , ku --> kú
Page 180 , 古 , ku --> kú
Page 180 , 估 , ku --> kú
Page 180 , 牯 , ku --> kú
Page 180 , 詁 , ku --> kú
Page 180 , 皷,鼓 , ku --> kú
Page 180 , 瞽 , ku --> kú
Page 181 , 羖 , ku --> kú
Page 181 , 𦙶,股 , ku --> kú
Page 181 , 賈 , ku --> kú
Page 181 , 蠱 , ku --> kú
Page 181 , 盬 , ku --> kú
Page 181 , 故 , ku --> kú
Page 181 , 顧 , ku --> kú
Page 182 , 僱,雇 , ku --> kú
Page 182 , 固 , ku --> kú
Page 182 , 錮 , ku --> kú
Page 182 , 痼 , ku --> kú
Page 189 , 曲 , k'uk --> kuk ( k'uk was in the description, but kuk shall be the original sound in this chapter)
Page 480 , 孫 , sun --> sün
Page 622 , 敦,惇 , tún --> tun
Page 622 , 𣎴 , tún --> tun
Page 622 , 燉 , tún --> tun
Page 622 , 頓 , tún --> tun
Page 622 , 遁,豚 , tún --> tun
Page 622 , 沌 , tún --> tun
Page 622 , 鈍 , tún --> tun
Page 623 , 湍 , t'ún --> t'un
Page 623 , 盾 , t'ún --> t'un
Page 623 , 楯 , t'ún --> t'un
Page 623 , 腯 , t'ún --> t'un
Page 623 , 彖 , t'ún --> t'un

Tones need to be checked again 
Page 24* , 沼
Page 119 , 䯻
Page 153 , 企
Page 155 , 魽
Page 162 , 挾
Page 179 , 罟
Page 184 , 颶
Page 191 , 狷,獧
Page 206 , 夬
Page 222 , 凛
Page 222 , 廩
Page 222 , 懍
Page 222 , 稟
Page 263 , 卵
Page 322 , 〇
Page 408 , 蹭
Page 518 , 掂
Page 565 , 鵲
Page 665 , 娩
Page 680 , 癊

**Comment by jyutnet** [comment]
Thanks!
