### ISSUE TITLE
1856_英華分韻撮要 pronunciation typo

### ISSUE THREAD

**Issue by HayaoAkiyama** [jyutnet/cantonese-books-data#19]
Page 28  𧽒  cháu--> ch'au
![image](https://user-images.githubusercontent.com/38387516/122615620-c3604b00-d0c3-11eb-8606-436700c911a6.png)

Page341 掩 im --> ím
![image](https://user-images.githubusercontent.com/38387516/122616021-8a74a600-d0c4-11eb-906e-2cf96145b909.png)

Page 20  贃  陰上 --> 陽上
![image](https://user-images.githubusercontent.com/38387516/122616202-e8a18900-d0c4-11eb-9985-2563ff8d1f57.png)

Page26* 詛  陰上 --> 陽去 in this case "原文缺聲調" should we use the original tone marked in the character?
![image](https://user-images.githubusercontent.com/38387516/122616454-53eb5b00-d0c5-11eb-9cfa-29b3600ade9e.png)

Page406 三|叁|〣 陰去 --> 陽去
![image](https://user-images.githubusercontent.com/38387516/122618075-759a1180-d0c8-11eb-9a9c-b2c53db6518d.png)

Page577 靚 陰去 --> 陽去
![image](https://user-images.githubusercontent.com/38387516/122618511-5d76c200-d0c9-11eb-9549-e31a2b9f090a.png)

Page648 縣 陽去 --> 陽平
![image](https://user-images.githubusercontent.com/38387516/122618654-a169c700-d0c9-11eb-848f-f3847b01e603.png)

**Comment by jyutnet** [comment]
Fixed in 04044a51a4cb6efbf0b315e66beceb534f5fc0c1. Thank you!
