### ISSUE TITLE
1856_英華分韻撮要 (Page 1-200) still missing extra pronunciation and etc...

### ISSUE THREAD

**Issue by HayaoAkiyama** [jyutnet/cantonese-books-data#20]
Page16  蘸 
![image](https://user-images.githubusercontent.com/38387516/122620794-d62c4d00-d0ce-11eb-9e39-5a3b2f4ff139.png)

Page35* 妯
![image](https://user-images.githubusercontent.com/38387516/122621032-5c489380-d0cf-11eb-8f96-05001fea3205.png)

Page37* 椿
the first sense should be "椿" (right side 春) example 椿堂, 椿萱.
the second sense should be "樁" (right side舂) example 一樁奇事.
But the dictionary mix it together. Better to descripted it as the way of 汨汩 and 陝陜.
![image](https://user-images.githubusercontent.com/38387516/122621232-e264da00-d0cf-11eb-88c6-efc04ed4c26a.png)

Page43  揮
![image](https://user-images.githubusercontent.com/38387516/122621656-22788c80-d0d1-11eb-84e8-d2fe8dfbc874.png)

Page43  隳
![image](https://user-images.githubusercontent.com/38387516/122621699-476cff80-d0d1-11eb-8d7b-d1272d9876eb.png)

Page44  沸
![image](https://user-images.githubusercontent.com/38387516/122621775-813e0600-d0d1-11eb-8854-134cfea2de18.png)

Page44  芾
![image](https://user-images.githubusercontent.com/38387516/122621803-a03c9800-d0d1-11eb-925b-b0ada03bd542.png)

Page45  分
![image](https://user-images.githubusercontent.com/38387516/122621849-c3ffde00-d0d1-11eb-92bd-1a5c3bbeaa2d.png)

Page46  墳
![image](https://user-images.githubusercontent.com/38387516/122621934-05908900-d0d2-11eb-9bbd-075b9c3baa20.png)

Page53  匪
![image](https://user-images.githubusercontent.com/38387516/122622026-53a58c80-d0d2-11eb-8454-f01227f23652.png)

Page58  枹
![image](https://user-images.githubusercontent.com/38387516/122622063-79329600-d0d2-11eb-8093-d9db39b2e07a.png)

Page120 蹊
![image](https://user-images.githubusercontent.com/38387516/122622332-4937c280-d0d3-11eb-85f9-d003895a0460.png)

155 撿 
![image](https://user-images.githubusercontent.com/38387516/122622369-708e8f80-d0d3-11eb-9bf0-a9f9b77e1e1c.png)

165 撟 
![image](https://user-images.githubusercontent.com/38387516/122622603-2b1e9200-d0d4-11eb-95e8-339f8a0486e9.png)

165 繳
![image](https://user-images.githubusercontent.com/38387516/122622632-3f628f00-d0d4-11eb-8a3d-cc446d349dec.png)

190 卷 
![image](https://user-images.githubusercontent.com/38387516/122622693-7a64c280-d0d4-11eb-8faa-300a67de668a.png)

191 圈 
![image](https://user-images.githubusercontent.com/38387516/122622736-a2542600-d0d4-11eb-8c95-07659100447f.png)

193 觀,覌 
![image](https://user-images.githubusercontent.com/38387516/122622769-c0ba2180-d0d4-11eb-9096-443524fd24bc.png)

**Comment by jyutnet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/38387516/122621032-5c489380-d0cf-11eb-8f96-05001fea3205.png)

Unlike "read" and "pronounced", the term "called" is tricky here. I can't really tell if that *chau3 lí5* is referring to another written form. So I left this in the explanation column. Ref:

![image](https://user-images.githubusercontent.com/7262459/122632818-c715c100-d107-11eb-9246-aa864d6cd240.jpg)

---

![image](https://user-images.githubusercontent.com/38387516/122621232-e264da00-d0cf-11eb-88c6-efc04ed4c26a.png)

I think this is different from the 汨/汩 and 陝/陜. For 汨 and 陝, two pronunciations exist, so it is obvious that the book had mixed up the similar forms. But for 椿, the pronunciation is still `ch'un1`, so the book seems to be using 椿 (its form and pronunciation) in place of 樁. There is not enough evidence to add 樁 as the alternate form.

WDYT?

**Comment by HayaoAkiyama** [comment]
Hi

Understood.
I agree with your logical thinking, and appreciate it.

Best regards.
Hayao Akiyama

**Comment by jyutnet** [comment]
Thank you. Other cases have been handled, closing.
