### ISSUE TITLE
1856_英華分韻撮要 (Page 201-400) still missing extra pronunciation and etc... 

### ISSUE THREAD

**Issue by HayaoAkiyama** [jyutnet/cantonese-books-data#21]
221 簕
![image](https://user-images.githubusercontent.com/38387516/122622972-6a99ae00-d0d5-11eb-939e-22721ea706ca.png)

230 踉
![image](https://user-images.githubusercontent.com/38387516/122623015-8c933080-d0d5-11eb-875e-314d060e0aed.png)

236 躒
![image](https://user-images.githubusercontent.com/38387516/122623074-bf3d2900-d0d5-11eb-8183-93a710d581d1.png)

238 臉
![image](https://user-images.githubusercontent.com/38387516/122623107-da0f9d80-d0d5-11eb-89de-91430e8d75f1.png)

259 蘲 there are no any other separate items in other pages to describe  the character "蘲". Better to add it.
![image](https://user-images.githubusercontent.com/38387516/122623330-95383680-d0d6-11eb-9c23-ea49291b5bc5.png)

268 唔 
![image](https://user-images.githubusercontent.com/38387516/122623462-1a235000-d0d7-11eb-9405-b50d7bb84f00.png)

312 杻
![image](https://user-images.githubusercontent.com/38387516/122623489-39ba7880-d0d7-11eb-9655-5f0c58a03f97.png)

312 橈
![image](https://user-images.githubusercontent.com/38387516/122623516-52c32980-d0d7-11eb-86de-b04e8ec06a2e.png)

371 胼
![image](https://user-images.githubusercontent.com/38387516/122623532-6a021700-d0d7-11eb-8ca4-dc1cecdcb5ed.png)

**Comment by jyutnet** [comment]
>259 蘲 there are no any other separate items in other pages to describe  the character "蘲". Better to add it.
![image](https://user-images.githubusercontent.com/38387516/122623330-95383680-d0d6-11eb-9c23-ea49291b5bc5.png)

For this and the similar one in #21 (釆), I agree it'd be nice if these characters are also present in the data file, but I need to think about the best way to handle them (if we are to), as I don't want to do it in a piecemeal fashion. I can find a similar case in P.238:
![p238](https://user-images.githubusercontent.com/7262459/122633909-a05a8900-d10d-11eb-8bda-78d26c2fac4e.jpg)

That 歛 is also only mentioned in the entry 斂. So I'd like to know the ball-park number of the characters of this kind first.

**Comment by jyutnet** [comment]
Opened #23 to track the "unlisted" characters. Other issues have been handled. Closing.
