### ISSUE TITLE
1856_英華分韻撮要 (Page 401-end) still missing extra pronunciation and etc...

### ISSUE THREAD

**Issue by HayaoAkiyama** [jyutnet/cantonese-books-data#22]
590 釆  pín  This character is not written in any other items in other pages. Better to add it.
![image](https://user-images.githubusercontent.com/38387516/122623811-8fdbeb80-d0d8-11eb-8fbe-758d88361193.png)

605 噂 
![image](https://user-images.githubusercontent.com/38387516/122623911-eb0dde00-d0d8-11eb-87be-cd7895c6f941.png)

610 蕞
![image](https://user-images.githubusercontent.com/38387516/122623944-0a0c7000-d0d9-11eb-8eed-8c964a393357.png)

675 髧
![image](https://user-images.githubusercontent.com/38387516/122623994-44760d00-d0d9-11eb-8413-b79da7d3f41e.png)

699 焬
![image](https://user-images.githubusercontent.com/38387516/122624041-71c2bb00-d0d9-11eb-9b95-af2d5ebc655c.png)

**Comment by jyutnet** [comment]
Opened #23 to track the "unlisted" characters in P.590. Other issues have been handled. Closing.
