### ISSUE TITLE
1856_英華分韻撮要 (Page 1-188) character variations , typo etc.

### ISSUE THREAD

**Issue by HayaoAkiyama** [jyutnet/cantonese-books-data#24]
001.0.07.0.21 呀: should add [ngá陽去] for this item.
380.0.01.0.12 呵|阿: should add [ngá陰去] for this item.

025.0.03.0.11 冊 is printed as "册"
![image](https://user-images.githubusercontent.com/38387516/122677084-a76fbd00-d21b-11eb-8a7e-bdca61eb3d4c.png)
025.0.04.0.11 柵 is printed as "栅"
![image](https://user-images.githubusercontent.com/38387516/122677088-ad659e00-d21b-11eb-9665-e21803743fa7.png)
Similar to Page423 刪,珊,姍,跚 are mixed with 冊 and 册 version.
Better to add all variants in "兼容字頭".
![image](https://user-images.githubusercontent.com/38387516/122677225-6fb54500-d21c-11eb-996e-cff0d2188a2b.png)
![image](https://user-images.githubusercontent.com/38387516/122677229-75128f80-d21c-11eb-8604-65fd3e24bc57.png)
![image](https://user-images.githubusercontent.com/38387516/122677239-7a6fda00-d21c-11eb-8ccf-183bcba87e6a.png)
![image](https://user-images.githubusercontent.com/38387516/122677247-8360ab80-d21c-11eb-846e-698b056f5540.png)

044.0.20.0.21 𧽒 should be "ch'au" instead of "ch'áu"
![image](https://user-images.githubusercontent.com/38387516/122677476-5e206d00-d21d-11eb-9bbc-9dfd1b6dabaa.png)

046.0.08.0.11 鈔|抄 should NOT include "抄" in this item,
in order to be consistent with other items of "interchanged with".
![image](https://user-images.githubusercontent.com/38387516/122677547-b9eaf600-d21d-11eb-8076-f344d3b5d986.png)

053.0.44.0.11	值
055.0.05.0.11	值
Better to add all variants of "(u503c)" and "(u5024)".
https://glyphwiki.org/glyph/u503c.png
https://glyphwiki.org/glyph/u5024-g.png
![image](https://user-images.githubusercontent.com/38387516/122677842-10a4ff80-d21f-11eb-8e3b-1dca5c1de482.png)

061.0.08.0.21	蒸
061.0.09.0.11	蒸
Two items are exactly same.

083.2.16.0.11	𠖥(字頭) 寵(兼容字頭)
103.0.05.1.11	虺|虫(字頭)
Both 寵 and 虫 are added in "additions and corrections", should be handled in a same way, 
either put in 字頭 or 兼容字頭.
![image](https://user-images.githubusercontent.com/38387516/122678117-5adab080-d220-11eb-92e1-ec512682bf8f.png)
![image](https://user-images.githubusercontent.com/38387516/122678122-61692800-d220-11eb-9ce5-7c2a0b8c9116.png)

084.0.03.1.11 㧤 chut꜆
pronunciation in list does not match with the book.
![image](https://user-images.githubusercontent.com/38387516/122678188-983f3e00-d220-11eb-928e-d6843062276a.png)

101.0.21.1.11	恍
101.0.21.2.11	怳
shall be in same row like "恍|怳", in order to be consistent with other items.
![image](https://user-images.githubusercontent.com/38387516/122678242-e3595100-d220-11eb-9c0d-5aa59da8d923.png)

102.0.18.7.11	稃 should be handled in the way of other extra characters.
![image](https://user-images.githubusercontent.com/38387516/122678322-4ba83280-d221-11eb-98d3-61faa2737a54.png)

104.0.03.0.11	福 is printed as "福"
better to add variants to "兼容字頭".
![image](https://user-images.githubusercontent.com/38387516/122678419-c3765d00-d221-11eb-9402-8dc44b62c745.png)

Page 715 missing "懽" in the list.
![image](https://user-images.githubusercontent.com/38387516/122678444-e9036680-d221-11eb-994f-f304dcba37e9.png)

Page 716 missing extra pronunciation of 蕸 in the list. 
![image](https://user-images.githubusercontent.com/38387516/122678476-118b6080-d222-11eb-81eb-2c63e1fe5b08.png)

Page 717 missing extra pronunciation of 頏 in the list.
![image](https://user-images.githubusercontent.com/38387516/122678536-4ac3d080-d222-11eb-9372-89af5f72fd3b.png)

Page 717 missing extra pronunciation of 儗 in the list.
![image](https://user-images.githubusercontent.com/38387516/122678725-f3723000-d222-11eb-8fef-e6052a8d6bb9.png)

149.0.34.0.21	pronunciation ꜁ím should NOT be added in character "𦦨", 
in order to be consistent with other "same as" items.
![image](https://user-images.githubusercontent.com/38387516/122678776-2288a180-d223-11eb-9402-58755e740baf.png)

155.0.03.0.11	枅(u6785)
better to add variant of "枅(u2f8e0)"
the following characters contain the similar part 幵/开, 
better to add variants to "兼容字頭" if there are Unicode for them.
Page89	開
Page111	研
Page119	筓
Page156	汧
Page156	豣
Page320	研
Page703	硏
Page703	郉

162.0.06.0.11	鑒|鑑 is printed as "𨰹"
better to add variants to "兼容字頭"
![image](https://user-images.githubusercontent.com/38387516/122679164-caeb3580-d224-11eb-8ca5-35e770dc8cc1.png)

Page175
臼 with pronunciation "kau" is missing in the list.
![image](https://user-images.githubusercontent.com/38387516/122679231-04bc3c00-d225-11eb-9d63-2981159b7559.png)

**Comment by jyutnet** [comment]
Thank you, the problems you reported in this issue should have been resolved as of 20b665cc7d7c5f5a9ad23e29d47fef17b407ca82. Some of the items have been fixed in previous commits. Here are a few things to note:

> 102.0.18.7.11 稃 should be handled in the way of other extra characters.
> ![image](https://user-images.githubusercontent.com/38387516/122678322-4ba83280-d221-11eb-98d3-61faa2737a54.png)

This is a bit tricky, as I've decided not to add the character with no attached pronunciation. But since it is marked with a tone I am keeping it.

> 104.0.03.0.11 福 is printed as "福"
> better to add variants to "兼容字頭".
> ![image](https://user-images.githubusercontent.com/38387516/122678419-c3765d00-d221-11eb-9402-8dc44b62c745.png)

福 (U+FA1B) is a CJK Compatibility Ideograph character and should only be used for round-trip compatibility with legacy encodings. I will try my best to avoid using these codepoints.

> 162.0.06.0.11 鑒|鑑 is printed as "𨰹"
> better to add variants to "兼容字頭"
> ![image](https://user-images.githubusercontent.com/38387516/122679164-caeb3580-d224-11eb-8ca5-35e770dc8cc1.png)

The glyph in the image looks like ⿰金𥃆, which is different from the character you have provided (the bottom-right component in 𨰹 is 金). 

> Page175
> 臼 with pronunciation "kau" is missing in the list.
> ![image](https://user-images.githubusercontent.com/38387516/122679231-04bc3c00-d225-11eb-9d63-2981159b7559.png)

Actually, the excerpt you attached comes from the "Additions and Corrections" section in P.718, and that "(175)" refers to the syllable index. In the dictionary, syllable 175 corresponds to the aspired form "K'au" (Kau is syllable 174). Also, the given pronunciation (kau + tone 5) translates to [gau5] in Jyutping, and this makes no sense in reading Cantonese. I think it's pretty safe to say that the book is using a wrong notation here.
