### ISSUE TITLE
1856_英華分韻撮要 (Page188-) character variations , typo etc.

### ISSUE THREAD

**Issue by HayaoAkiyama** [jyutnet/cantonese-books-data#25]
P720
missing extra pronounciation of 鱖.
![image](https://user-images.githubusercontent.com/38387516/124341512-cf85f580-dbf7-11eb-86e5-c91c5176c947.png)

P721
missing extra pronunciation of 囒
the tone of 欄 did not match with the book. 
![image](https://user-images.githubusercontent.com/38387516/124341646-c34e6800-dbf8-11eb-99d4-1d0a393859fb.png)

P721
missing extra pronunciation of 莨
![image](https://user-images.githubusercontent.com/38387516/124341683-06a8d680-dbf9-11eb-8a44-fe3c8576024c.png)

P251
賂 should be also included in the extra pronunciation.
![image](https://user-images.githubusercontent.com/38387516/124341885-bcc0f000-dbfa-11eb-8dc9-7753f9e00c4b.png)

P259
multiple rows of 擂 with the same pronunciation.

P265
a spical form 吼 was not described in the databse.
![image](https://user-images.githubusercontent.com/38387516/124341972-5b4d5100-dbfb-11eb-986c-688f07ea4bdc.png)

P306
泥,坭 should be written in the same row but not separated.
to be consistent with the format of the whole database.
![image](https://user-images.githubusercontent.com/38387516/124342091-3c9b8a00-dbfc-11eb-82e0-7d2e7bad08d5.png)

P316
original character in the book should be 𭺜(u2de9c)
![image](https://user-images.githubusercontent.com/38387516/124342189-25a96780-dbfd-11eb-8b3d-c5f00ef343f3.png)

P324
There are no Chinese characters for this item in the book.
It is better not to create a character (𠼮) for it according to the policy of the page.
![image](https://user-images.githubusercontent.com/38387516/124342223-60ab9b00-dbfd-11eb-8693-e61335cf2698.png)

P334
愞,懦 should be written in the same row but not separated.
to be consistent with the format of the whole database.
![image](https://user-images.githubusercontent.com/38387516/124342288-d6176b80-dbfd-11eb-8e78-e7d2f5a2c80d.png)

P451
should be written in the same row but not separated.
to be consistent with the format of the whole database.
![image](https://user-images.githubusercontent.com/38387516/124342481-4672bc80-dbff-11eb-9094-16be135cdeb3.png)

P471
should be written in the same row but not separated.
to be consistent with the format of the whole database.
![image](https://user-images.githubusercontent.com/38387516/124342492-5f7b6d80-dbff-11eb-840a-f5863c17bcd8.png)

P500
missing a character 澹
![image](https://user-images.githubusercontent.com/38387516/124342511-7621c480-dbff-11eb-9de1-68871a9e8407.png)

P702
missing a character  形(u2f899)
![image](https://user-images.githubusercontent.com/38387516/124342663-6ce52780-dc00-11eb-88b5-bf23cd4e0339.png)

P704
yéung should be also added to 暎.
![image](https://user-images.githubusercontent.com/38387516/124342626-1e378d80-dc00-11eb-97be-39c49d21a892.png)

**Comment by jyutnet** [comment]
Hi,

Thank you for the report. One item is left unchanged:

>P704
>yéung should be also added to 暎.
>![image](https://user-images.githubusercontent.com/38387516/124342626-1e378d80-dc00-11eb-97be-39c49d21a892.png)

I understand what you mean, but due to lack of confidence and similar cases I am keeping it in the explanation field.

Others are fixed.

Thanks again!
