### ISSUE TITLE
「淥」字缺少釋義

### ISSUE THREAD

**Issue by Serious54088** [jyutnet/cantonese-books-data#29]
《广州话正音字典》

**渌**

①河流名，在湖南省。➁清澈:～水澹澹。➂同“漉”，过滤：洗～。➃同“醁”，美酒：杯中～。➄<方>烫：～亲只脚（脚被烫伤了）｜用滚水～下筷子（用开水烫一下筷子）。

**Comment by jyutnet** [comment]
Resolved in f800ad3202c1e3afaaed20e51bd2c3bb0ff01019. Thank you!

**Comment by Serious54088** [comment]
This is an automatic reply, confirming that your email was received. I will reply as soon as possible. Thank you!
