### ISSUE TITLE
資料庫沒有收錄「𭌱」

### ISSUE THREAD

**Issue by Serious54088** [jyutnet/cantonese-books-data#30]
𱒨（𭌱）

《廣州話正音字典》p245

![image](https://github.com/jyutnet/cantonese-books-data/assets/28971568/4bb67c30-73f1-4f6d-a824-7d9d0245fb82)

**Comment by HayaoAkiyama** [comment]
簡體字唔好收啦

**Comment by Serious54088** [comment]
This is an automatic reply, confirming that your email was received. I will reply as soon as possible. Thank you!

**Comment by Serious54088** [comment]
> 簡體字唔好收啦

唔好意思，搞錯咗，我以爲網站冇收錄到繁體的𡄵字。
