### ISSUE TITLE
1855_初學粵音切要:遺漏及異體

### ISSUE THREAD

**Issue by HayaoAkiyama** [jyutnet/cantonese-books-data#6]
遺漏:
2頁6行:亟:見息(有入聲標記)
2頁10行:駭:下代:據錯遺備考#1補上
2頁16行:令:耒丁(有平聲標記)
3頁13行:共:共動(無標記)
6頁17行:荷:下何(無標記)
7頁12行:𪓽(U+2A4FD):同何
11頁16行:㠯(U+382F):由始
13頁15行:𢛳(U+226F3):丁則
14頁1行:𢦏(U+2298F):則哀
14頁4行:𢧜(U+229DC):杖不
14頁17行:⿰育攵:丑別

異體:
取「書中原字」或「常見字型」，目前並不統一。
1頁9行:呌[叫]
2頁6行:互[亙]
3頁7行:兎[兔]
3頁8行:兠[兜]
3頁11行:兪[俞]
3頁11行:喩[喻]
3頁17行:册[冊]
3頁17行:栅[柵]
3頁17行:删[刪]
3頁17行:姗[姍]
4頁12行:刹[剎]
5頁12行:𦋐[罩]
5頁19行:卽[即]
5頁19行:喞[唧]
6頁5行:刧[劫]
6頁5行:丢[丟]
6頁8行:𠬛[殳]
6頁8行:沒[没]
6頁9行:歿[殁]
7頁3行:羣[群]
7頁3行:呑[吞]
7頁5行:告[吿]
7頁8行:嵒[喦]
7頁16行:囘[回]
8頁2行:揑[捏]
8頁6行:𡈼[壬]
8頁19行:关[灷] (原書註: 古作灷)
9頁1行:奇[竒]
10頁3行:寛[寬]
10頁12行:𡭽[𡭴]
10頁12行:𨻶[隙]
11頁15行:𣏌[杞]
11頁15行:汜[𣲆]
12頁2行:刋[刊]
12頁3行:筓[笄]
13頁2行:强[強]
13頁4行:緑[綠]
13頁5行:彚[彙]
13頁7行:顔[顏]
13頁13行:騐[驗]
13頁15行:贃[賺]
13頁15行:窻[窗]
14頁2行:鵝[鵞]
18頁14行:爲[為]
18頁14行:僞[偽]
18頁14行:嬀[媯]
20頁20行:温[溫]
20頁20行:氲[氳]
20頁20行:蕰[薀]
21頁1行:藴[蘊]
21頁1行:愠[慍]

所有切字:
囘[回]
亷[廉]
爲[為]
𡭽[𡭴]

據錯遺備考# 5，「尨明當」似是修訂原切音，而非增加字頭。
尨:篇當⇒尨:明當

**Comment by ktshek** [comment]
8e03f8f 的變更也包括將本無相關字碼的部首以 IDS 形式表示。又「`7頁12行:𪓽(U+2A4FD):同何`」的字頭我使用了「鼉」字。

有關異體字問題，抱歉上次的說法可能引起誤解，我再解釋一下。

《初學粵音切要》的資料檔是粵音典籍數碼化工作首個成品，並無一套處理異體字問題的方案（當時找尋異體字字碼也沒有現在那麼方便）。不過由於資料檔主要是用在網頁供人搜尋，所以大致是以方便搜尋、輸入為依歸，並不強求依從原字模（所謂方便輸入，自然是指在繁體中文環境下所用輸入法所提供的字集，也多少有受中文系統發展等歷史因素所影響）。後來《粵音資料集叢》將不同的書籍資料整合，終於要面對異體字的搜尋問題，加入了異體字表處理，才慢慢形成原始文件輸入時「首先考慮遵從原字模寫法的字碼」的做法（但仍僅限字頭。其他內容如釋義、前言不會強依原字模，也不會為每個不依從原字模的字形加註）。但「採用書中原字」也不是金科玉律，因為說到底，我做數碼化的重點是在讀音上，而不是「忠實呈現原書所用字模寫法」上。更何況，很多時候原書對於字模字形的選擇純屬偶然。像你回報的「兔」字，部首明明是「兔」（而上方作刀），字條卻作兎。如果依原文，一來導致部首與字條不一致，二來其實也做不到「忠實呈現」（「兔」的字形跟一般系統上看到的還是不同）。而兔字條前的「免」部，書中只有此字用了「從刀」寫法，在 Unicode 屬於 CJK兼容字 U+FA32，但也似乎只有某些地區的字型才會看到從刀的寫法。還有「呌」在「丩」部，顯然是「叫」的訛體；「俞」部則之有俞、揄、喻三字用右下作巜，其餘均作刂；「奇」字一字條作「奇」另一條作「竒」，這些明顯是受當時雕板印刷限制。這種情況我是傾向在輸入時順道理順之（頂多加上附註，至於俞兪這類更是十分普遍的印刷體差異，再作說明恐嫌囉唆）。因為我製作數碼檔案是希望提供一個「有用」的版本方便使用者，但如「呌」這類字如果真的照原文輸入恐怕無法達到這個目的。至於跟不一致無關的，假如是屬於在 Unicode 本來應該統一的字形，我一般會使用慣常輸入的那一個，但也不是絕對。之前「劫刧」，我不改的原因是因為「刧」並不十分罕見，又不是本應統一的字形，並且是 HKSCS 字符，所以決定遵從原書字形，而不是單純因為這是原書字形才不改。這種做法的確很可能會發生前後不一致的問題，不過正如之前說的，我做數碼化的重點是在讀音，而且工作還在進行，輸入時要找尋某一罕用字的 Unicode 碼位已經花去不少時間，實在覺得不值得將花時間花在逐一尋找各個字模在 Unicode 是否有符合該字形但不是慣用的字碼方面。當然，現在這個「視情況而定」的做法相信不能令所有人都滿意，而像我一方面說希望「部首與部首下的字形保持一致」，一方面又容許之前「單」這個部首下採用原書的「鼉」字而不改為「𪓽」，感覺也是有點自打嘴巴。唯有希望大家在這方面多多包涵。

無論如何，還是非常感謝閣下回報的異體字問題，我有時間會視情況逐字處理，但未必都會按原書字形修改字頭（或者會在備註欄補充），敬請諒解（反切字會影響程式處理，更是傾向保留不動）。長遠來說，我會多加一個異體欄，方便使用者搜尋，這時候應可「還原」多一些異體字。

**Comment by HayaoAkiyama** [comment]
To Mr.Shek

閣下有如此周詳考慮，令人安心。
小弟只是將校對結果照版全盤奉上，並無意扭曲用字準則。此系統功德無量，日後定必福澤後世。

共勉之！

Best regards,

2019/02/20 23:28、ktshek <notifications@github.com>のメール:

**Comment by ktshek** [comment]
先生抬舉，愧不敢當。承蒙多番賜正，嘉惠社群，由衷感激。

**Comment by jyutnet** [comment]
謹將先生所提出，有關異體字問題之決定略述如下：

#### 已修改、取原字模寫法

3頁8行:兠[兜]
5頁12行:𦋐[罩]
6頁8行:𠬛[殳]——之前已修正為「𠬛」
7頁8行:嵒[喦]（其實嵒、喦是兩個字，這裏應是「嵒」，原資料檔有錯）
8頁2行:揑[捏]
13頁2行:强[強]

#### 不須修改、取原字模寫法

14頁2行:鵝[鵞]
6頁8行:沒[没]
6頁9行:歿[殁]
7頁3行:羣[群]
13頁13行:騐[驗]
13頁15行:贃[賺]
13頁15行:窻[窗]

#### 不作修改

1頁9行:呌[叫]——「叫」與部首相合，保留校訂註。
2頁6行:互[亙]——應是指「𠀕」？不過原字模「互」中是一橫，跟「𠀕」也有不同，不如取常用形。
3頁7行:兎[兔]——「兔」與部首相合，但會加註。
6頁5行:刧[劫]——已解釋。
8頁6行:𡈼[壬]——𡈼、壬是兩個不同的字，「𡈼」粵音「挺」，見於「廷」「呈」等字；「壬」粵音「吟」，見於妊、飪等字。
9頁1行:奇[竒]——「奇」與部首相合，而此是多音字，另一音字模亦作「奇」，故不從原書。但會加註。
11頁15行:𣏌[杞]——「𣏌」是「耜」的異體，粵音「似」或「治」，與「杞」不同。
11頁15行:汜[𣲆]——原因如校訂註：字頭作「汜」，讀音與部首均不合，似宜作「𣲆」。惟「𣲆」音「己」亦欠憑據，姑保留原字備考。

* 其餘保留不動的，是本應在 Unicode 統一，但因 source separation rule 而被分離的字。對於這些字，我主要是以存在於 Big5/HKSCS 的字做首選，若兩寫同時見於 Big5/HKSCS 則再酙酌決定（至於有些 Ext-B 看來應該 unitfy 但不知為何分離的字，處理方法相同，像之前提到的𠀕字）。在本書而言也會考慮與部首字形的統一性。

### 其他

8頁19行:关[灷](原書註: 古作灷)——已補上
