### ISSUE TITLE
點解會有 kwut3 同 kut3 嘅對立呢？

### ISSUE THREAD

**Issue by sgalal** [jyutnet/cantonese-books-data#9]
<div lang="yue-HK">

「[括](https://jyut.net/query?q=%E6%8B%AC)」字有 <span lang="yue-Latn-HK">kwut3</span> 同 <span lang="yue-Latn-HK">kut3</span> 兩個讀音嘅對立：

![《粵音資料集叢》中目前可能存在嘅一個問題](https://user-images.githubusercontent.com/32255369/74097875-47a7d300-4b4c-11ea-908c-26ff40faf704.jpg)

粵拼基本上係唔允許 <span lang="yue-Latn-HK">kwu/gwu</span> 嘅串法，而且我諗冇區分呢兩個嘅人。所以點解會有 kwut3 同 kut3 嘅對立呢？

</div>

**Comment by jyutnet** [comment]
茲轉述香港語言學學會網站「[粵拼答問](https://www.lshk.org/faq-on-jyutping)」一文內容：

---
C. [uː]前的[k(w)(h)]
問：到底“古“應該拼寫成 gu2 還是 gwu2 ？「觀塘」的「觀」應該是 gun1 還是 gwun1？
    
答：
這牽涉好幾方面的問題。 g 和 gw 之間有對立，例如 gai1 ~ gwai1，因此兩者肯定有別。至於兩者的分別在什麼地方，則存在爭議。首先，這w是否介音？現代粵語語音作為自足的共時音系，優化的處理是粵語無介音， 除非作為普通話音系的附庸則另作別論。（當然，作跨方言比較和歷時分析的時候也可將就着看為有介音。）事實是，香港和海外一般認為粵語無介音，內地則兩說參半。粵拼的音系立場是粵語無介音，因此， gw 是個雙字母(digraph)，代表單個聲母，換句話說， g 和 gw 是兩個不同的粵語聲母。然則這兩個聲母的分別又在什麼地方呢？有人說：g 不圓唇，gw 圓唇；事實是，goe 的 g 明顯地圓唇，而 gwi 的 gw，發音雖然有唇的參與，卻並非真正意義的圓唇。既然圓唇並非 gw 之所以區別於 g 的特徵，那麼在圓唇韻腹 [uː] 前也就不能先驗地排除有 gw 的可能性。在本會《粵語拼音字彙》第一版的六名編者中，就有三名認為 [uː] 前的 g/gw 是 gw, 另外三名則認為是 g；最後出版時處理為 g, 不無偶然性。其他粵音字彙字典，也是兩種處理都有。至於香港政府的慣常英譯方式，則把「古」拼作 ku，卻又把「觀」拼作 kwun，一方面反映出它欠缺系統性，另一方面也反映了粵語人對此處 gw~g 的取捨存在變異性。要指出，無論取 g 還是取 gw，都沒有改變粵語的聲母韻母系統，一套拼音方案（包括我們的粵拼）在兩者之間的取捨是中立的。
    
k 和 kw 是 g 和 gw 的送氣版本。上面所說的，都可同時套用於 k 和 kw 的關係。

------

可見粵拼並無「唔允許」 gwu/kwut 一類拼法；kw、k 有對立無容置疑，kwut3、kut3 讀音亦有別。這跟多數人在圓唇韻腹 [uː] 前不區分 kw/k 或 gw/g ，即 gu/gwu(古)、gui/gwui(攰)、gwun/gun(觀)、 kui/kwui(繪)、kwut/kut(括) 可視作自由變體，沒有衝突。至於《道漢字音》同時為一字注上這二音，原因為何，又為甚麼只有括、䒷二字有此特殊安排？現在恐怕只能猜測——可能是編者在兩音之間舉棋不定，或是忠實地反映當時的異讀。
